### ISSUE TITLE
Safe class renaming conflict

### ISSUE THREAD

**Issue by cossssmin** [maizzle/framework#111]
https://github.com/maizzle/framework/commit/84b6dbdaf54ded5d3a1ac00561e4b4c21776f9a8 introduced a bug where two different utility classes would be renamed using the same name.

If you have this in the `tailwind.config.js`:

```js
module.exports = {
  theme: {
    width: {
      '2/5': '40%',
      '2.5': '0.625rem',
    }
  }
}
```

Then you get:

```css
.w-2-5 {
  width: 40% !important;
}

.w-2-5 {
  width: 0.625rem !important;
}
```

This can be fixed by replacing `.` with a `_`  instead of `-`, so you'd get this:

```css
.w-2-5 {
  width: 40% !important;
}

.w-2_5 {
  width: 0.625rem !important;
}
```
