### ISSUE TITLE
Some spacing and line break issues after 4.7.3

### ISSUE THREAD

**Issue by evrpress** [maizzle/framework#1160]
- Maizzle Version: 4.7.3

Thanks for the quick update. I've noticed a small "issue" when using ',' in style blocks:

**with 4.7.2**
```css
body, .body {
      	...
}

@media screen {
      		.screen-font-quicksand {
      				font-family: 'Quicksand', ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important;
      		}
      }
```

**with 4.7.3**
```css
body,
.body {
	...
}
@media screen {
.screen-font-quicksand {
	font-family:
	"Quicksand",
	ui-sans-serif,
	system-ui,
	-apple-system,
	"Segoe UI",
	sans-serif !important;
}
```
If possible line-breaks should not get changed otherwise we get a high column of selectors (like [from them](https://github.com/maizzle/starter-mailchimp/blob/70ea013e6133100d49d83538156cc92588e0c412/src/layouts/main.html#L19))

The `<pre>`  tags are also off:

**with 4.7.2 (and [my fix](https://github.com/maizzle/framework/issues/1156#issuecomment-1909654395))** 
```html
				<pre>

		Content

	
				</pre>
``` 
**with 4.7.3**     
```html
				<pre>

		Content

	</pre>
```
I'm aware that `<pre>` tags preserve tabs and spaces so maybe the miss-alignment is preferable.
