### ISSUE TITLE
problem with important in css

### ISSUE THREAD

**Issue by Frolipon** [maizzle/framework#1436]
When using a css function directly in the HTML, the CSS class is generated with an `!important`.
Example:
```html
<div class="bg-green hover:bg-red">
  My Block
<div>
```
Will generate
```css
.bg-green:hover {
  background-color: #00FF00 !important;
}
```

But if I create a css class like:
```css
.bg_custom {
  @apply bg-green hover:bg-red;
}
```
In a block like that:
```html
<div class="bg_custom">
  My Block
<div>
```
Then the output CSS will miss the `!important`:
```css
.bg_custom:hover {
  background-color: #00FF00;
}
```

A workaround for that at the moment would be to force Tailwind to do it writing it like that:
```css
.bg_custom {
  @apply bg-green hover:!bg-red;
}
```

Just to let you know that the code behaves differently depending on where you use it ;-)
