### ISSUE TITLE
Gradients and key:value theme colors

### ISSUE THREAD

**Issue by cossssmin** [maizzle/framework#34]
Currently, `tailwindcss-gradients` cannot correctly generate gradients based on the default key:value pair from Tailwind's default color scheme.

So this:

```js
linearGradients: theme => ({
  colors: theme('colors'),
    directions: {
      't': 'to top',
    },
}),
```

Would generate a class like:

```css
.bg-gradient-t-gray {
  background-image: linear-gradient(to top, transparent, [object Object]) !important;
}
```

**Solution**

Need to create a dedicated `gradients` key in `tailwind.config.js` and define colors as in the [docs](https://github.com/benface/tailwindcss-gradients).
