### ISSUE TITLE
Replace deprecated `word-break` with `overflow-wrap` in `reset.css`

### ISSUE THREAD

**Issue by jokull** [maizzle/framework#581]
I suggest a slight adjustment to the default reset.css:

```css
/*! purgecss start ignore */
body {
  @apply m-0 p-0 w-full;
  -webkit-font-smoothing: antialiased;
}

img {
  border: 0;
  @apply max-w-full leading-full align-middle;
}

p,
h1,
h2,
h3,
h4,
h5,
h6 {
  overflow-wrap: break-word;
}
/*! purgecss end ignore */
```

Here I've removed `word-break: break-word;` from body which is a deprecated value of this property and scoped a new `overflow-wrap: break-word;` but only on p and header elements. 

More info:

- https://www.joshwcomeau.com/css/custom-css-reset/
- https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
