### ISSUE TITLE
Custom utility classes + media queries with `inlineCSS`

### ISSUE THREAD

**Issue by jebax** [maizzle/framework#616]
- Maizzle Version: 3.7.2
- Node.js Version: 14.7.3

Hi there,

I've got a couple of custom utility classes that I created because I was reusing the same styles everywhere, and they apply different styles depending on light/dark mode. For example, this custom class:

```css
.primary-text-color {
  @apply text-black dark:text-white
}
```

Compiles to this CSS:
```css
.primary-text-color {
  color: #000000;
}
@media (prefers-color-scheme: dark) {
  .primary-text-color {
    color: #ffffff;
  }
}
```

This differs from using the standard Tailwind utility classes, because of the use of `!important` - for example, if I did `class="text-black dark:text-white` then `!important` would get added to the media query for dark mode.

So, when I use `inlineCSS` (i.e. in production), the light styles get inlined. This means the media query above will never apply because it doesn't include `!important`.

Is there any way to configure my maizzle app to get around this? Or do you need to disable inline CSS when using custom utility classes + media queries? Otherwise, I think this may be a bug?

Thanks!
