### ISSUE TITLE
Keep CSS Hacks From Being Removed

### ISSUE THREAD

**Issue by jkappers-ga** [maizzle/framework#646]
- Maizzle Version: 3.7.3
- Node.js Version: 16.14.0

I'm having the same issue as expresed in #628 

I'm using a similar hack:

```css
div > u + .body .gmail-android-block {
  display: block !important;
}
```

I can't figure out a combination of config that will not strip this from the build.

I've tried using the `safelist` config and `<style data-embed>`.

Any advice on how to keep such hacks from being stripped out?

Thank you in advance!
