### ISSUE TITLE
Only largest breakpoint is applied

### ISSUE THREAD

**Issue by stvnthomas** [maizzle/framework#965]
- Maizzle Version: 4.4.4
- Node.js Version: 19.7.0

Only the largest breakpoint is applied when multiple breakpoints are used. Breakpoints are written in the build files from smallest to largest `max-width` so the larger breakpoints have higher precedence.  From the example, `xs:w-48` is overridden by `sm:w-56`.

```html
<img class="w-64 sm:w-56 xs:w-48" src="/images/logo.png" alt="Example">
```

```css
@media (max-width: 425px) {
    .xs-w-48 {
        width: 192px !important
    }
}
@media (max-width: 600px) {
    .sm-w-56 {
        width: 224px !important
    }
}
```

The issue is fixed if the order of the media queries is reversed. A regression from #36? But it applies to local and build files.
